language: go
go:
  - stable
  - "1.19"
  - "1.18"
  - "1.17"
  - "1.16"
  - "1.15"
  - "1.14"
  - "1.13"
install:
# v1
  - go get -t .
# v2
  - cd v2
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  - cd ..
after_success:
  - cd v2
  - curl -s https://codecov.io/bash | bash
